#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3

readonly MAXMIND_SIGNUP_URL='https://www.maxmind.com/en/geolite2/signup'
readonly MAXMIND_ACCOUNT_URL='https://www.maxmind.com/en/accounts/current/edit'
readonly MAXMIND_LICENSE_URL='https://www.maxmind.com/en/accounts/current/license-key'
readonly GEOIPUPDATE_VERSION='8.0.0'
readonly GEOIPUPDATE_ARCHIVE="geoipupdate_${GEOIPUPDATE_VERSION}_linux_amd64.tar.gz"
readonly GEOIPUPDATE_ARCHIVE_ROOT="geoipupdate_${GEOIPUPDATE_VERSION}_linux_amd64"
readonly GEOIPUPDATE_URL="https://github.com/maxmind/geoipupdate/releases/download/v${GEOIPUPDATE_VERSION}/${GEOIPUPDATE_ARCHIVE}"
readonly GEOIPUPDATE_SHA256='941eb4dd8c1eafb6ee1d56ccd5f4c62ffbdaca5f65a9f9cadc4008c8d805f2a2'
readonly GEOIPUPDATE_HOST='https://updates.maxmind.com'
readonly GEOIP_EDITION='GeoLite2-City'

script_directory=$(
  cd -- "$(dirname -- "${BASH_SOURCE[0]}")" || exit 1
  pwd
)
[[ -f $script_directory/paths.sh ]] || {
  printf '%s\n' 'geo setup: paths.sh is missing; re-run install.sh.' >&2
  exit 1
}
# shellcheck source=scripts/paths.sh
source "$script_directory/paths.sh"
egress_geo_resolve_paths setup

geo_configuration_path="$geo_configuration_directory/GeoIP.conf"
geo_database_path="$geo_application_root/GeoLite2-City.mmdb"
geo_updater_directory="$geo_application_root/updater"
geo_updater_path="$geo_updater_directory/geoipupdate"
existing_values_file=''
pending_configuration=''
install_workspace=''

cleanup_setup() {
  if [[ -n $existing_values_file && -e $existing_values_file ]]; then
    rm -f -- "$existing_values_file"
  fi
  if [[ -n $pending_configuration && -e $pending_configuration ]]; then
    rm -f -- "$pending_configuration"
  fi
  if [[ -n $install_workspace && -d $install_workspace ]]; then
    rm -rf -- "$install_workspace"
  fi
}
trap cleanup_setup EXIT

require_command() {
  command -v "$1" >/dev/null 2>&1 ||
    egress_geo_fail "$1 was not found on PATH."
}

configuration_value() {
  local expected=$1
  local line
  local value=''
  local matches=0

  [[ -f $geo_configuration_path ]] || return 1
  while IFS= read -r line || [[ -n $line ]]; do
    if [[ $line =~ ^${expected}[[:space:]]+(.+)$ ]]; then
      matches=$((matches + 1))
      value=${BASH_REMATCH[1]}
    fi
  done < "$geo_configuration_path"

  [[ $matches -eq 1 ]] || return 1
  printf '%s' "$value"
}

valid_account_id() {
  [[ $1 =~ ^[1-9][0-9]*$ ]]
}

valid_license_key() {
  [[ -n $1 && ! $1 =~ [[:space:]] ]]
}

prepare_existing_values() {
  local account_id
  local license_key

  mkdir -p -- "$geo_configuration_directory"
  chmod 0700 "$geo_configuration_directory"
  existing_values_file=$(mktemp \
    "$geo_configuration_directory/.setup-values.XXXXXX")
  chmod 0600 "$existing_values_file"
  account_id=$(configuration_value AccountID || true)
  license_key=$(configuration_value LicenseKey || true)
  if valid_account_id "$account_id"; then
    printf 'MAXMIND_ACCOUNT_ID=%s\n' "$account_id" >> "$existing_values_file"
  fi
  if valid_license_key "$license_key"; then
    printf 'MAXMIND_LICENSE_KEY=%s\n' "$license_key" >> "$existing_values_file"
  fi
  ENV_FILE=$existing_values_file
}

capture_account_id() {
  while true; do
    ask MAXMIND_ACCOUNT_ID 'Paste the account ID:'
    if valid_account_id "$MAXMIND_ACCOUNT_ID"; then
      return
    fi
    warn 'The account ID must be a positive number.'
  done
}

capture_license_key() {
  while true; do
    ask_secret MAXMIND_LICENSE_KEY 'Paste the license key (hidden):'
    if valid_license_key "$MAXMIND_LICENSE_KEY"; then
      return
    fi
    warn 'The license key must be non-empty and contain no whitespace.'
  done
}

write_pending_configuration() {
  mkdir -p -- "$geo_configuration_directory" "$geo_application_root"
  chmod 0700 "$geo_configuration_directory"
  pending_configuration=$(mktemp \
    "$geo_configuration_directory/.GeoIP.conf.XXXXXX")
  {
    printf 'AccountID %s\n' "$MAXMIND_ACCOUNT_ID"
    printf 'LicenseKey %s\n' "$MAXMIND_LICENSE_KEY"
    printf 'Host %s\n' "$GEOIPUPDATE_HOST"
    printf 'DatabaseDirectory %s\n' "$geo_application_root"
    printf 'EditionIDs %s\n' "$GEOIP_EDITION"
  } > "$pending_configuration"
  chmod 0600 "$pending_configuration"
}

install_geoipupdate() {
  mkdir -p -- "$geo_application_root" "$geo_updater_directory"
  install_workspace=$(mktemp -d \
    "$geo_application_root/.geoipupdate.install.XXXXXX")
  local archive_path="$install_workspace/$GEOIPUPDATE_ARCHIVE"

  curl --fail --location --silent --show-error \
    --proto '=https' --tlsv1.2 \
    --output "$archive_path" \
    "$GEOIPUPDATE_URL"

  local checksum
  checksum=$(sha256sum "$archive_path")
  checksum=${checksum%%[[:space:]]*}
  [[ $checksum == "$GEOIPUPDATE_SHA256" ]] ||
    egress_geo_fail 'geoipupdate archive checksum verification failed.'

  tar --extract --gzip --file "$archive_path" \
    --directory "$install_workspace"
  local extracted_updater
  extracted_updater="$install_workspace/$GEOIPUPDATE_ARCHIVE_ROOT/geoipupdate"
  [[ -x $extracted_updater ]] ||
    egress_geo_fail 'verified archive does not contain geoipupdate.'

  install -m 0755 -- "$extracted_updater" \
    "$install_workspace/geoipupdate"
  mv -T -- "$install_workspace/geoipupdate" "$geo_updater_path"
  rm -rf -- "$install_workspace"
  install_workspace=''
}

update_and_verify_database() {
  "$geo_updater_path" -f "$pending_configuration"
  [[ -s $geo_database_path ]] ||
    egress_geo_fail 'GeoLite2 City update did not create a database.'

  "$geo_launcher_path" setup --verify-database ||
    egress_geo_fail 'geo could not read the updated City database.'
}

for command_name in curl sha256sum tar install; do
  require_command "$command_name"
done
[[ -x $geo_launcher_path ]] ||
  egress_geo_fail 'geo is not installed; run install.sh first.'
[[ $geo_application_root != *$'\n'* && $geo_application_root != *$'\r'* ]] ||
  egress_geo_fail 'the user data path contains an unsupported newline.'
umask 077

banner 'GeoLite setup'

stage 'Create or access a GeoLite account'
say 'GeoLite access requires its specific free signup and license agreement.'
open_url "$MAXMIND_SIGNUP_URL"
step 'New users: complete the GeoLite form and accept the GeoLite license.'
step 'Existing GeoLite users: use Sign In instead of creating another account.'
step 'Complete the email verification and sign in before continuing.'
note 'This wizard never asks for or stores your MaxMind password.'
pause 'Press Enter after your GeoLite account is ready.'

stage 'Collect the updater credentials'
prepare_existing_values
say 'First copy the numeric account ID shown at the top of Account Information.'
open_url "$MAXMIND_ACCOUNT_URL"
capture_account_id
say 'Next create a key named egress-geo; MaxMind displays the full key once.'
open_url "$MAXMIND_LICENSE_URL"
step "Select 'Generate new license key', name it egress-geo, and confirm."
step 'Copy the generated key before leaving the page.'
printf '  %sKeep the license key private; enter it only at the hidden prompt.%s\n' \
  "$RED" "$RESET"
capture_license_key
rm -f -- "$existing_values_file"
existing_values_file=''

stage 'Install GeoLite2 City'
say 'The updater is checksum-verified before it can replace the installed copy.'
write_pending_configuration
unset MAXMIND_ACCOUNT_ID MAXMIND_LICENSE_KEY
install_geoipupdate
update_and_verify_database
mv -T -- "$pending_configuration" "$geo_configuration_path"
pending_configuration=''

finish
say 'This product includes GeoLite Data created by MaxMind, available from https://www.maxmind.com.'
say 'Run: geo'
